### ISSUE TITLE
Extension throw error in frontend

### ISSUE THREAD

**Issue by atelier-interaktiv** [Rathch/chr_wallsio#4]
After install and include the extension and set the contentelement with plugin chr_wallsio and setting wall-url, it throw the following error in the frontend:
Call to undefined method TYPO3\CMS\Extbase\Configuration\ConfigurationManager::getContentObjectRenderer()

**Comment by Rathch** [comment]
Hi, 
I fixes this issue in Developement.
Thx for reporting

**Comment by Rathch** [comment]
Fixed the TER version in release 0.1.1
